name: AntiCropTrample
version: '1.0-SNAPSHOT'
main: me.jojjjo147.antiCropTrample.AntiCropTrample
api-version: '1.21'
permissions:
  antiCropTrample.bypass:
    description: Allows you to trample crops
    default: false